"""Query Pauli distance through the unmodified trusted CSS SAT certifier.

The three binary coordinates per physical qubit represent X, Y, Z. Projection
pi(u,v,w)=(u+v,v+w) has kernel generated by (I|I|I). Adding that kernel to the
lifted stabilizer rows yields a CSS code whose X-distance is exactly the source
Pauli distance. This does not create an official stabilizer-board certificate.
"""

import argparse
import copy
import hashlib
import json
import sys
import time
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[2]
sys.path[:0] = [str(ROOT / "verify"), str(ROOT / "research/kit")]
import gf2
import heuristic_distance as hd
import sat_certify
from coordination import unique_path
from submit import save_submission


def supports(matrix):
    return [list(map(int, np.flatnonzero(row))) for row in matrix]


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("candidate", type=Path)
    parser.add_argument("--seconds", type=float, default=60)
    parser.add_argument("--bound", type=int, default=None, help="Search weight <= bound; default source d-1.")
    args = parser.parse_args()
    source = json.loads(args.candidate.read_text())
    A, B = hd.stabilizer_matrices(source)
    n = source["n"]
    rank_s = gf2.rank(np.concatenate([A, B], axis=1))
    zero = np.zeros_like(A)
    eye = np.eye(n, dtype=np.int8)
    HX = np.vstack([np.concatenate([A, zero, B], axis=1), np.concatenate([eye, eye, eye], axis=1)])
    HZ = np.concatenate([B, A ^ B, A], axis=1)
    rank_x = gf2.rank(HX)
    rank_z = gf2.rank(HZ)
    assert not ((HX @ HZ.T) % 2).any()
    assert rank_x == rank_s + n and rank_z == rank_s
    assert 3 * n - rank_x - rank_z == 2 * source["k"]
    wit = source["distance"]["P"]["witness"]
    x = np.zeros(n, dtype=np.int8)
    z = x.copy()
    x[wit["X"]] = 1
    z[wit["Z"]] = 1
    lifted = np.concatenate([x & (1 - z), x & z, z & (1 - x)])
    assert hd._valid_logical(lifted, HZ, HX)
    assert int(lifted.sum()) == source["distance"]["d"]
    bound = args.bound if args.bound is not None else source["distance"]["d"] - 1
    query = {
        "name": f"X-distance query for {source['name']}",
        "n": 3 * n,
        "checks": {"X": supports(HX), "Z": supports(HZ)},
        "distance": {"d": bound + 1},
    }
    target = Path(__file__).resolve().parent / f"pauli-sat-{n}-{source['k']}-bound{bound}.json"
    result = {
        "source": str(args.candidate),
        "source_sha256": hashlib.sha256(args.candidate.read_bytes()).hexdigest(),
        "distance_query_bound": bound,
        "embedding": {
            "source_n": n,
            "source_rank": rank_s,
            "derived_n": 3 * n,
            "derived_rank_X": rank_x,
            "derived_rank_Z": rank_z,
            "derived_k": 3 * n - rank_x - rank_z,
            "commutation_checked": True,
            "source_witness_lift_valid": True,
            "lifted_witness_weight": int(lifted.sum()),
        },
        "official_board_certification": False,
        "status": "running",
    }
    target.write_text(json.dumps(result, indent=2) + "\n")
    print("EMBEDDING", json.dumps(result["embedding"]), flush=True)
    start = time.monotonic()
    answer = sat_certify.certify(query, tlim=args.seconds)
    result.update(
        {"status": "completed", "elapsed_seconds": round(time.monotonic() - start, 3), "trusted_sat_result": answer}
    )
    xside = answer["sides"]["X"]
    if xside["status"] == "SAT":
        e = np.zeros(3 * n, dtype=np.int8)
        e[xside["witness"]] = 1
        v = np.concatenate([e[:n] ^ e[n : 2 * n], e[n : 2 * n] ^ e[2 * n :]])
        assert hd.valid_pauli_logical(v, A, B)
        pauli = hd.pauli_witness(v, n)
        weight = int(hd.pauli_weight_rows(v[None, :], n)[0])
        corrected = copy.deepcopy(source)
        corrected["name"] = f"[[{n},{source['k']},{weight}]]"
        corrected["distance"] = {"d": weight, "P": {"value": weight, "confidence": "upper_bound", "witness": pauli}}
        output = unique_path(
            str(args.candidate.with_name(f"{n}-{source['k']}-{weight}-pauli-sat-witness.json")), corrected
        )
        errors = save_submission(corrected, output)
        if errors:
            raise RuntimeError(errors)
        result.update({"source_logical_found": {"weight": weight, "witness": pauli}, "saved_candidate": output})
    elif xside["status"] == "UNSAT":
        result["mathematical_pauli_lower_bound"] = bound + 1
        result["mathematical_distance_exact"] = bound + 1 == source["distance"]["d"]
    target.write_text(json.dumps(result, indent=2) + "\n")
    print(json.dumps(result, indent=2), flush=True)


if __name__ == "__main__":
    main()
